version: '3.9'
services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./docker-cache/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_DATABASE=ghost_db